zh_CN:
  avatar: Avatar
  avatar-description: >-
    We recommend an image of at least 512x512 (or 1:1 ratio).You can upload a
    PNG, JPG under 5MB
  choose-file: Choose file
  save: Save
  preview: Preview
  customisation: Customisation
  banner: Banner
  banner-description: Recommend with 1440x262 pixels with GIF, PNG, JPG, JPEG
  profile-background: Profile Background
  profile-background-description: Recommend with 16:9 ratio with PNG, JPG, JPEG
  password: Password
  password-change: Password Change
  old-password: Old Password
  new-password: New Password
  repeat-password: Repeat Password
  profile: Profile
  user-information: User Infomation
  username: Username
